export enum Screens {
    MAIN = 'MAIN',
    REPORTS = 'REPORTS',
    REGISTER_LIST = 'REGISTER_LIST',
    REGISTER = 'REGISTER',
    ADMIN = 'ADMIN',
    ADD_USER_BASIC = 'ADD_USER_BASIC',
    ADD_USER_BASIC_EDIT = 'ADD_USER_BASIC_EDIT',
    ADD_USER_ALLERGIES = 'ADD_USER_ALLERGIES',
    ADD_USER_ALLERGIES_EDIT = 'ADD_USER_ALLERGIES_EDIT',
    SEARCH_USER = 'SEARCH_USER',
    ALLERGIES = 'ALLERGIES',
    ATTENDANCES = 'ATTENDANCES'
}