export enum Screens {
    LOADING = 'LOADING',
    SIGN_UP = 'SIGN_UP',
    LOGIN = 'LOGIN',
    MAIN = 'MAIN',
    REPORTS = 'REPORTS',
    REGISTER_LIST = 'REGISTER_LIST',
    REGISTER = 'REGISTER',
    ADMIN = 'ADMIN',
    USER_PROFILE = 'USER_PROFILE',
    ADD_USER_BASIC = 'ADD_USER_BASIC',
    ADD_USER_EMERGENCY_CONTACT = 'ADD_USER_EMERGENCY_CONTACT',
    ADD_USER_ALLERGIES = 'ADD_USER_ALLERGIES',
    SEARCH_USER = 'SEARCH_USER',
    ALLERGIES = 'ALLERGIES',
    ATTENDANCES = 'ATTENDANCES'
}